# Generated by Django 2.2.7 on 2019-12-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField()),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Store')),
            ],
        ),
    ]
